version: '3.2'
services:
  jenkins:
    build:
      context: ./jenkins
    image: 'jenkins/jenkins:lts'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
    - ../volumes/jenkins:/jenkins_config'